name: "Setup Build Environment"
description: "Sets up the CI build environment for building .s9pk packages"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          clang \
          libclang-dev \
          squashfs-tools-ng \
          qemu-user-static
      shell: bash

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install start-cli
      run: |
        ARCH=$(uname -m)
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ASSET_NAME="start-cli_${ARCH}-${OS}"
        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/Start9Labs/start-os/releases \
          | jq -r '[.[].assets[] | select(.name=="'"$ASSET_NAME"'")] | first | .browser_download_url')
        if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" = "null" ]; then
          echo "Error: Could not find asset '$ASSET_NAME' in Start9Labs/start-os releases"
          exit 1
        fi
        curl -fsSL "$DOWNLOAD_URL" -o /tmp/start-cli
        sudo install -m 755 /tmp/start-cli /usr/local/bin/start-cli
        rm /tmp/start-cli
        echo ""
        echo "start-cli: $(start-cli --version)"
      shell: bash
