name: "Free Disk Space"
description: "Removes unnecessary files to free up disk space"

runs:
  using: "composite"
  steps:
    - name: Free up disk space
      run: |
        echo "Disk space before cleanup:"
        df -h
        echo "Removing unnecessary packages and files..."
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h
      shell: bash
